global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "spring-boot-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "server:8081" ]
    basic_auth:
      username: admin
      password: admin