spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
  application:
    name: messenger-clone
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/chatapp
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: jpa
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        format_sql: true
        highlight_sql: true
    # open-in-view: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
      client-type: lettuce
      # username: username
      # password: password
      # ssl:
      #   enabled: true
      #   bundle: general
    elasticsearch:
      repositories:
        enabled: true
  mvc:
    problemdetails:
      enabled: true
  flyway:
    clean-disabled: false
    enabled: true
  elasticsearch:
    uris: http://localhost:9200

  kafka:
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 4
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: decade
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "com.decade.practice.dto.events"

logging:
  level:
    root: INFO
    com.decade.practice: DEBUG
    org.springframework: INFO


actuator:
  user:
    name: admin
    password: admin
    roles: OPS
server:
  port: 8080
  error:
    include-message: always
  servlet:
    session:
      cookie:
        same-site: Lax
  # ssl:
  #   bundle: general

frontend:
  host:
    address: http://localhost:4200

jwt:
  secret: vcl-vcl-vcl-vcl-vcl-vcl-vcl-vcl-vcl-vcl

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,env,bean,info,prometheus
  endpoint:
    health:
      show-details: ALWAYS

aws:
  s3:
    endpoint: http://localhost:4566
    region: ap-southeast-1
    bucket: decade-bucket
    access:
      id: decade
      secret: decade

